eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

userInfoInterceptor:
  enable: true

spring:
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8090
      enabled: true

feign:
  sentinel:
    enabled: true