server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: test-service
            uri: lb://test-service
            predicates:
              - Path=/test/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/