server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
          - id: test-service
            uri: lb://test-service
            predicates:
              - Path=/test/**
      default-filters:
        - Authentication=1  # AuthenticationGatewayFilter Priority

em:
  jwt:
    location: classpath:JwtSignKey.jks
    alias: emall
    password: emallpwd
    tokenTTL: 30m
  auth:
    excludePaths:
      - /test/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/