server:
  port: 8081

spring:
  application:
    name: test-service
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/emall

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka